# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df66a169edae92e2bfebb8ad47404e09ebf63676b4f10aeea0ab52934c12f6e47c71af3ca7ca70886b65acaa430b67812192fe3de856574245d8a6af69e4cb2

test:
  secret_key_base: db5ca94b95b706310cc28b1b7b99a240e681a15c2bc1e1f9ca43a652bc0051b4e68929dacb8beb57ffd85f544115158eaf73495c37a6ae267d62bcd70eac4619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
